name = "gloss"
version = "0.0.1"

description = "A Gleam package"
licences = ["Apache-2.0"]
repository = { type = "github", user = "Sylvance", repo = "gloss" }
# links = [{ title = "Website", href = "https://gleam.run" }]
dependencies = { gleam_stdlib = "~> 0.36"}
dev-dependencies = { gleeunit = "~> 1.0"}
