name: test

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.0.0"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - name: Build Docs
        run: gleam docs build

      - name: Copy Docs to Documentation Folder
        run: cp -r build/dev/docs/gloss/* docs

      - name: Commit Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: omosamurai
          commit_user_email: 9350722+Sylvance@users.noreply.github.com
          commit_message: Update Gleam Docs
          push_options: --force
